oc_core_homepage:
    path:     /
    defaults: { _controller: OCCoreBundle:Acceuil:index }
    
oc_core_contact:
    path:    /Contact
    defaults: { _controller: OCCoreBundle:Contact:contact }
   
